// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyRM-RKPzOEd7qhVzSp7K957y2BkcMYbs',
    appId: '1:508635875276:web:4aeb37030c7033502cbf69',
    messagingSenderId: '508635875276',
    projectId: 'wmp-tdl',
    authDomain: 'wmp-tdl.firebaseapp.com',
    storageBucket: 'wmp-tdl.firebasestorage.app',
    measurementId: 'G-JB27BM8XW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTqmdIQWHsC3h7eaqu7Rdnpo7xayMM2RQ',
    appId: '1:508635875276:android:29e368c44f7a86a52cbf69',
    messagingSenderId: '508635875276',
    projectId: 'wmp-tdl',
    storageBucket: 'wmp-tdl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdgOk2E9-B_I90s7Tszb17d1KLo3hfDHQ',
    appId: '1:508635875276:ios:930b38402ebb46062cbf69',
    messagingSenderId: '508635875276',
    projectId: 'wmp-tdl',
    storageBucket: 'wmp-tdl.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdgOk2E9-B_I90s7Tszb17d1KLo3hfDHQ',
    appId: '1:508635875276:ios:930b38402ebb46062cbf69',
    messagingSenderId: '508635875276',
    projectId: 'wmp-tdl',
    storageBucket: 'wmp-tdl.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyRM-RKPzOEd7qhVzSp7K957y2BkcMYbs',
    appId: '1:508635875276:web:6918cd6356a78c232cbf69',
    messagingSenderId: '508635875276',
    projectId: 'wmp-tdl',
    authDomain: 'wmp-tdl.firebaseapp.com',
    storageBucket: 'wmp-tdl.firebasestorage.app',
    measurementId: 'G-6FTLPKEYEQ',
  );
}
